---
name: LoginSystem
main: LoginSystem\LoginSystem
version: 6.0.0
api: 3.0.0
load: POSTWORLD
author: tukikage7127
description: this is the LoginSystem
commands:
  register:
    usage: ~
    description: アカウント登録
  login:
    usage: ~
    description: ログイン認証
  unregister:
    usage: ~
    description: アカウント削除
  cpardon:
    usage: ~
    description: Banの解除
    permission: cpardon.command
  dld:
    usage: ~
    description: アカウント削除
    permission: icban.command
permissions:
  cpardon:
    default: op
    description: Allows using all the LoginSystem things
  cpardon.command:
    default: op
    description: Allows using all the LoginSystem command
...
